/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        "on-error": "#690005",
        "tertiary-fixed": "#dbe1ff",
        "surface-bright": "#3d392f",
        "on-surface-variant": "#d0c5af",
        "on-primary": "#3c2f00",
        "tertiary-container": "#97b0ff",
        "on-secondary-fixed-variant": "#544600",
        "primary-container": "#d4af37",
        "error-container": "#93000a",
        "secondary-fixed-dim": "#e9c400",
        "background": "#16130b",
        "on-secondary-fixed": "#221b00",
        "on-tertiary-container": "#254188",
        "secondary": "#fff9ef",
        "surface-tint": "#e9c349",
        "surface-container-low": "#1f1b13",
        "inverse-surface": "#eae1d4",
        "surface-container-lowest": "#110e07",
        "secondary-container": "#ffdb3c",
        "tertiary-fixed-dim": "#b4c5ff",
        "on-surface": "#eae1d4",
        "on-secondary-container": "#725f00",
        "primary": "#f2ca50",
        "on-tertiary": "#082b72",
        "on-primary-fixed-variant": "#574500",
        "primary-fixed": "#ffe088",
        "inverse-on-surface": "#343027",
        "on-tertiary-fixed-variant": "#27438a",
        "on-error-container": "#ffdad6",
        "surface-container-high": "#2d2a21",
        "surface": "#16130b",
        "on-primary-fixed": "#241a00",
        "error": "#ffb4ab",
        "on-background": "#eae1d4",
        "surface-variant": "#38342b",
        "inverse-primary": "#735c00",
        "outline": "#99907c",
        "outline-variant": "#4d4635",
        "on-secondary": "#3a3000",
        "tertiary": "#bfcdff",
        "surface-container-highest": "#38342b",
        "on-primary-container": "#554300",
        "surface-dim": "#16130b",
        "surface-container": "#231f17",
        "secondary-fixed": "#ffe16d",
        "on-tertiary-fixed": "#00174b",
        "primary-fixed-dim": "#e9c349"
      },
      fontFamily: {
        serif: ['"Playfair Display"', 'Georgia', 'serif'],
        cinzel: ['"Cinzel"', 'serif'],
        sans: ['"Plus Jakarta Sans"', 'Inter', 'sans-serif'],
        headline: ['"Hanken Grotesk"', 'Georgia', 'serif'],
        "headline-xl": ["Hanken Grotesk"],
        "display-lg": ["Hanken Grotesk"],
        "headline-lg": ["Hanken Grotesk"],
        body: ['Inter', 'system-ui', 'sans-serif'],
        "body-md": ["Inter"],
        "body-sm": ["Inter"],
        "body-lg": ["Inter"],
        label: ['Geist', 'system-ui', 'sans-serif'],
        "label-sm": ["Geist"],
        "label-md": ["Geist"]
      },
      fontSize: {
        "headline-xl": ["32px", { "lineHeight": "1.2", "letterSpacing": "-0.01em", "fontWeight": "600" }],
        "body-md": ["16px", { "lineHeight": "1.5", "fontWeight": "400" }],
        "display-lg": ["48px", { "lineHeight": "1.1", "letterSpacing": "-0.02em", "fontWeight": "600" }],
        "label-sm": ["10px", { "lineHeight": "1", "letterSpacing": "0.08em", "fontWeight": "600" }],
        "body-sm": ["14px", { "lineHeight": "1.4", "fontWeight": "400" }],
        "body-lg": ["18px", { "lineHeight": "1.6", "fontWeight": "400" }],
        "label-md": ["12px", { "lineHeight": "1", "letterSpacing": "0.05em", "fontWeight": "500" }],
        "headline-lg": ["24px", { "lineHeight": "1.3", "fontWeight": "500" }]
      },
      spacing: {
        "md": "16px",
        "xl": "32px",
        "sm": "8px",
        "margin-mobile": "16px",
        "xxl": "48px",
        "margin-desktop": "40px",
        "gutter": "20px",
        "unit": "4px",
        "lg": "24px",
        "xs": "4px"
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        md:      '0.375rem',
        lg: '0.25rem',
        xl: '0.5rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        '4xl':   '2rem',
        full: '0.75rem',
      },
      boxShadow: {
        gold:  '0 0 20px rgba(230,195,100,0.2)',
        vault: '0 20px 40px rgba(0,0,0,0.5)',
        glow:  '0 0 25px rgba(201,168,76,0.5)',
      },
    },
  },
  plugins: [],
};
