/** @type {import('tailwindcss').Config} */
export default {
  darkMode: 'class',
  content: ['./index.html', './src/**/*.{js,ts,jsx,tsx}'],
  theme: {
    extend: {
      colors: {
        'surface':                   '#131313',
        'surface-dim':               '#131313',
        'surface-bright':            '#3a3939',
        'surface-variant':           '#353534',
        'surface-container-lowest':  '#0e0e0e',
        'surface-container-low':     '#1c1b1b',
        'surface-container':         '#201f1f',
        'surface-container-high':    '#2a2a2a',
        'surface-container-highest': '#353534',
        'background':                '#131313',
        'on-surface':                '#e5e2e1',
        'on-surface-variant':        '#d0c5b2',
        'on-background':             '#e5e2e1',
        'primary':                   '#e6c364',
        'primary-container':         '#c9a84c',
        'on-primary':                '#3d2e00',
        'secondary':                 '#e3c466',
        'tertiary':                  '#cbc6bf',
        'outline':                   '#99907e',
        'outline-variant':           '#4d4637',
        'error':                     '#ffb4ab',
        'error-container':           '#93000a',
        'on-error':                  '#690005',
      },
      fontFamily: {
        headline: ['"Noto Serif"', 'Georgia', 'serif'],
        body:     ['Inter', 'system-ui', 'sans-serif'],
        label:    ['Inter', 'system-ui', 'sans-serif'],
      },
      borderRadius: {
        DEFAULT: '0.125rem',
        md:      '0.375rem',
        xl:      '0.5rem',
        '2xl':   '1rem',
        '3xl':   '1.5rem',
        '4xl':   '2rem',
        full:    '0.75rem',
      },
      boxShadow: {
        gold:  '0 0 20px rgba(230,195,100,0.2)',
        vault: '0 20px 40px rgba(0,0,0,0.5)',
        glow:  '0 0 25px rgba(201,168,76,0.5)',
      },
    },
  },
  plugins: [],
};
